#<nick kandydata>
#  glosy:<oddane glosy na kandydata>
#  kto: <osoby ktore glosowaly na kandydata>
glosowali: []
kandydaci:
  0:
    name: Test
    glosy: 0
    kto: []
    lore:
      - §6§l1.§c§b
      - §6§l2.§c§b
      - §6§l3.§c§b
  1:
    name: Cesarz
    glosy: 0
    kto: [ ]
    lore:
      - §6§l1.§c§b
      - §6§l2.§c§b
      - §6§l3.§c§b
  2:
    name: Tomek
    glosy: 0
    kto: [ ]
    lore:
      - §6§l1.§c§b
      - §6§l2.§c§b
      - §6§l3.§c§b
  3:
    name: Tomek
    glosy: 0
    kto: [ ]
    lore:
      - §6§l1.§c§b
      - §6§l2.§c§b
      - §6§l3.§c§b
  4:
    name: Tomek
    glosy: 0
    kto: [ ]
    lore:
      - §6§l1.§c§b
      - §6§l2.§c§b
      - §6§l3.§c§b
  5:
    name: Tomek
    glosy: 0
    kto: [ ]
    lore:
      - §6§l1.§c§b
      - §6§l2.§c§b
      - §6§l3.§c§b
  6:
    name: Tomek
    glosy: 0
    kto: [ ]
    lore:
      - §6§l1.§c§b
      - §6§l2.§c§b
      - §6§l3.§c§b
  7:
    name: Tomek
    glosy: 0
    kto: [ ]
    lore:
      - §6§l1.§c§b
      - §6§l2.§c§b
      - §6§l3.§c§b
  8:
    name: Tomek
    glosy: 0
    kto: [ ]
    lore:
      - §6§l1.§c§b
      - §6§l2.§c§b
      - §6§l3.§c§b
  9:
    name: Czarek
    glosy: 0
    kto: [ ]
    lore:
      - §6§l1.§c§b
      - §6§l2.§c§b
      - §6§l3.§c§b

