0:
  material: DIAMOND_PICKAXE
  itemname: Kilof Menela
  itelore: Menelski Kilof
  rarity: 0
1:
  material: DIAMOND_PICKAXE
  itemname: Kilof Menela
  itelore: Menelski Kilof
  rarity: 0
2:
  material: DIAMOND_PICKAXE
  itemname: Kilof Menela
  itelore: Menelski Kilof
  rarity: 0
3:
  material: DIAMOND_PICKAXE
  itemname: Kilof Menela
  itelore: Menelski Kilof
  rarity: 0
4:
  material: DIAMOND_PICKAXE
  itemname: Kilof Menela
  itelore: Menelski Kilof
  rarity: 0
5:
  material: DIAMOND_PICKAXE
  itemname: Kilof Menela
  itelore: Menelski Kilof
  rarity: 0
6:
  material: DIAMOND_PICKAXE
  itemname: Kilof Menela
  itelore: Menelski Kilof
  rarity: 0
7:
  material: DIAMOND_PICKAXE
  itemname: Kilof Menela
  itelore: Menelski Kilof
  rarity: 0
8:
  material: DIAMOND_PICKAXE
  itemname: Kilof Menela
  itelore: Menelski Kilof
  rarity: 0