#drop chances
rubin-drop-chance: 0.0025 #default - 350
netheritium-drop-chance: 0.0001 #default - 3000
meteor-drop-chance: 0.001 #default - 800
platinum-drop-chance: 0.0005 #default - 1600
bedrock-drop-chance: 0.0001 #default - 3500

#custom ores drops
rubin-enable: true
netheritium-enable: false
meteor-enable: false
platinum-enable: false
bedrock-enable: false